package httpapi

import "net/http"

func (s *Server) Routes() http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /api/health", s.health)
	mux.HandleFunc("GET /api/auth/status", s.authStatus)
	mux.HandleFunc("GET /api/auth/providers", s.authProviders)
	mux.HandleFunc("GET /api/auth/{provider}/start", s.oauthStart)
	mux.HandleFunc("GET /api/auth/{provider}/callback", s.oauthCallback)
	mux.HandleFunc("POST /api/auth/{provider}/callback", s.oauthCallback)
	mux.HandleFunc("POST /api/auth/setup", s.setup)
	mux.HandleFunc("POST /api/auth/register", s.register)
	mux.HandleFunc("POST /api/auth/login", s.login)
	mux.HandleFunc("POST /api/auth/logout", s.logout)
	mux.Handle("GET /api/auth/account", s.requireAuth(http.HandlerFunc(s.getAccount)))
	mux.Handle("PUT /api/auth/password", s.requireAuth(http.HandlerFunc(s.setPassword)))
	mux.Handle("GET /api/auth/{provider}/link/start", s.requireAuth(http.HandlerFunc(s.oauthLinkStart)))
	mux.Handle("DELETE /api/auth/identities/{provider}", s.requireAuth(http.HandlerFunc(s.unlinkOAuthIdentity)))
	mux.Handle("DELETE /api/auth/account", s.requireAuth(http.HandlerFunc(s.deleteAccount)))
	mux.Handle("POST /api/assets/images", s.requireAuth(http.HandlerFunc(s.uploadImageAsset)))
	mux.Handle("GET /api/assets/image-proxy", s.requireAuth(http.HandlerFunc(s.proxyImageURL)))
	mux.Handle("GET /api/assets/{assetID}", s.requireAuth(http.HandlerFunc(s.getAsset)))
	mux.Handle("GET /api/campaigns", s.requireAuth(http.HandlerFunc(s.listCampaigns)))
	mux.Handle("POST /api/campaigns", s.requireAuth(http.HandlerFunc(s.createCampaign)))
	mux.Handle("GET /api/campaigns/{campaignID}", s.requireAuth(http.HandlerFunc(s.getCampaign)))
	mux.Handle("GET /api/campaigns/{campaignID}/encounters", s.requireAuth(http.HandlerFunc(s.listCampaignEncounters)))
	mux.Handle("POST /api/campaigns/{campaignID}/encounters", s.requireAuth(http.HandlerFunc(s.createEncounter)))
	mux.Handle("POST /api/campaigns/{campaignID}/long-rest", s.requireAuth(http.HandlerFunc(s.longRestCampaign)))
	mux.Handle("POST /api/campaigns/{campaignID}/long-rest/undo", s.requireAuth(http.HandlerFunc(s.undoLongRestCampaign)))
	mux.Handle("POST /api/campaigns/{campaignID}/npcs", s.requireAuth(http.HandlerFunc(s.linkCampaignCreature)))
	mux.Handle("DELETE /api/campaigns/{campaignID}/npcs/{creatureID}", s.requireAuth(http.HandlerFunc(s.unlinkCampaignCreature)))
	mux.Handle("GET /api/players", s.requireAuth(http.HandlerFunc(s.listPlayers)))
	mux.Handle("GET /api/players/{playerID}", s.requireAuth(http.HandlerFunc(s.getPlayer)))
	mux.Handle("PUT /api/players/{playerID}", s.requireAuth(http.HandlerFunc(s.updatePlayer)))
	mux.Handle("DELETE /api/players/{playerID}", s.requireAuth(http.HandlerFunc(s.deletePlayer)))
	mux.Handle("POST /api/campaigns/{campaignID}/players", s.requireAuth(http.HandlerFunc(s.createPlayer)))
	mux.Handle("GET /api/library/creatures", s.requireAuth(http.HandlerFunc(s.listCreatures)))
	mux.Handle("POST /api/library/creatures", s.requireAuth(http.HandlerFunc(s.createCreature)))
	mux.Handle("GET /api/library/creatures/{creatureID}", s.requireAuth(http.HandlerFunc(s.getCreature)))
	mux.Handle("PUT /api/library/creatures/{creatureID}", s.requireAuth(http.HandlerFunc(s.updateCreature)))
	mux.Handle("DELETE /api/library/creatures/{creatureID}", s.requireAuth(http.HandlerFunc(s.deleteCreature)))
	mux.Handle("GET /api/library/creatures/{creatureID}/campaigns", s.requireAuth(http.HandlerFunc(s.getCreatureCampaigns)))
	mux.Handle("GET /api/library/creatures/{creatureID}/actions", s.requireAuth(http.HandlerFunc(s.listCreatureActions)))
	mux.Handle("POST /api/library/creatures/{creatureID}/actions", s.requireAuth(http.HandlerFunc(s.createCreatureAction)))
	mux.Handle("PUT /api/library/creatures/{creatureID}/actions", s.requireAuth(http.HandlerFunc(s.replaceCreatureActions)))
	mux.Handle("POST /api/library/creatures/{creatureID}/actions/copy-template", s.requireAuth(http.HandlerFunc(s.copyActionTemplateToCreature)))
	mux.Handle("PATCH /api/library/creatures/{creatureID}/actions/reorder", s.requireAuth(http.HandlerFunc(s.reorderCreatureActions)))
	mux.Handle("GET /api/library/creatures/{creatureID}/spellcasting", s.requireAuth(http.HandlerFunc(s.getCreatureSpellcasting)))
	mux.Handle("PUT /api/library/creatures/{creatureID}/spellcasting", s.requireAuth(http.HandlerFunc(s.upsertCreatureSpellcasting)))
	mux.Handle("GET /api/library/spells", s.requireAuth(http.HandlerFunc(s.listSpells)))
	mux.Handle("POST /api/library/spells", s.requireAuth(http.HandlerFunc(s.createSpell)))
	mux.Handle("GET /api/action-templates", s.requireAuth(http.HandlerFunc(s.listActionTemplates)))
	mux.Handle("POST /api/action-templates", s.requireAuth(http.HandlerFunc(s.createActionTemplate)))
	mux.Handle("PUT /api/action-templates/{templateID}", s.requireAuth(http.HandlerFunc(s.updateActionTemplate)))
	mux.Handle("GET /api/action-templates/{templateID}/usage", s.requireAuth(http.HandlerFunc(s.getActionTemplateUsage)))
	mux.Handle("DELETE /api/action-templates/{templateID}", s.requireAuth(http.HandlerFunc(s.deleteActionTemplate)))
	mux.Handle("GET /api/encounters/{encounterID}", s.requireAuth(http.HandlerFunc(s.getEncounter)))
	mux.Handle("PUT /api/encounters/{encounterID}", s.requireAuth(http.HandlerFunc(s.updateEncounter)))
	mux.Handle("DELETE /api/encounters/{encounterID}", s.requireAuth(http.HandlerFunc(s.deleteEncounter)))
	mux.Handle("POST /api/encounters/{encounterID}/clone", s.requireAuth(http.HandlerFunc(s.cloneEncounter)))
	mux.Handle("POST /api/encounters/{encounterID}/combatants", s.requireAuth(http.HandlerFunc(s.createEncounterCombatants)))
	mux.Handle("POST /api/encounters/{encounterID}/combatants/add-all-players", s.requireAuth(http.HandlerFunc(s.addAllPlayersToEncounter)))
	mux.Handle("PUT /api/encounter-combatants/{combatantID}", s.requireAuth(http.HandlerFunc(s.updateEncounterCombatant)))
	mux.Handle("DELETE /api/encounter-combatants/{combatantID}", s.requireAuth(http.HandlerFunc(s.deleteEncounterCombatant)))
	mux.Handle("POST /api/encounters/{encounterID}/start", s.requireAuth(http.HandlerFunc(s.startEncounter)))
	mux.Handle("GET /api/encounter-runs/{runID}", s.requireAuth(http.HandlerFunc(s.getEncounterRun)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/roll-initiative", s.requireAuth(http.HandlerFunc(s.rollInitiativeCommand)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/set-initiative", s.requireAuth(http.HandlerFunc(s.setInitiativeCommand)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/reorder-initiative", s.requireAuth(http.HandlerFunc(s.reorderInitiativeCommand)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/begin", s.requireAuth(http.HandlerFunc(s.beginEncounterRunCommand)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/next-turn", s.requireAuth(http.HandlerFunc(s.nextTurnCommand)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/previous-turn", s.requireAuth(http.HandlerFunc(s.previousTurnCommand)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/manual-hp", s.requireAuth(http.HandlerFunc(s.manualHPCommand)))
	mux.Handle("POST /api/encounter-runs/{runID}/combatants", s.requireAuth(http.HandlerFunc(s.addRunCombatants)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/execute-action", s.requireAuth(http.HandlerFunc(s.executeActionCommand)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/resolve-action-damage", s.requireAuth(http.HandlerFunc(s.resolveActionDamageCommand)))
	mux.Handle("PUT /api/encounter-run-combatants/{combatantID}", s.requireAuth(http.HandlerFunc(s.updateEncounterRunCombatant)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/roll-check", s.requireAuth(http.HandlerFunc(s.rollCheckCommand)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/death-save", s.requireAuth(http.HandlerFunc(s.deathSaveCommand)))
	mux.Handle("POST /api/encounter-runs/{runID}/commands/undo", s.requireAuth(http.HandlerFunc(s.undoCommand)))
	mux.Handle("POST /api/encounter-runs/{runID}/end", s.requireAuth(http.HandlerFunc(s.endEncounterRun)))
	mux.Handle("POST /api/dev/seed-test-data", s.requireAuth(http.HandlerFunc(s.seedTestData)))

	return s.withCSRF(withJSON(withRecover(s.log, mux)))
}
