export type Item = {
  id: string;
  name: string;
  category: string;
  itemType: string;
  rarity: string;
  attunement: boolean;
  valueAmount: number;
  valueUnit: string;
  weight: number;
  description: string;
  properties: string[];
  damage: Record<string, unknown>;
  armorClass: Record<string, unknown>;
  data: Record<string, unknown>;
  librarySource: "user" | "standard";
  readOnly: boolean;
  sourceKey: string;
  sourceLabel: string;
  createdAt: string;
  updatedAt: string;
};

export type ItemFormState = {
  name: string;
  category: string;
  itemType: string;
  rarity: string;
  attunement: boolean;
  valueAmount: string;
  valueUnit: string;
  weight: string;
  description: string;
  properties: string[];
  damageDice: string;
  damageType: string;
  weaponCategory: string;
  weaponRange: string;
  normalRange: string;
  longRange: string;
  thrownNormalRange: string;
  thrownLongRange: string;
  twoHandedDamageDice: string;
  mastery: string;
  armorCategory: string;
  acMode: "base" | "bonus";
  acBase: string;
  acBonus: string;
  dexModifier: string;
  strengthMinimum: string;
  stealthDisadvantage: boolean;
  shield: boolean;
  toolCategory: string;
  ability: string;
  utilize: string;
  craftOutputs: string;
  variants: string;
  focusFamily: string;
  focusVariant: string;
  focusUsage: string;
  quantity: string;
  compatibleWeapon: string;
  contents: string;
  uses: string;
  charges: string;
  effect: string;
  consumableType: string;
  consumeBehavior: string;
  serviceDuration: string;
  quality: string;
  speed: string;
  carryingCapacity: string;
  cargo: string;
  crew: string;
  passengers: string;
  vehicleArmorClass: string;
  vehicleHitPoints: string;
  inventoryCarried: boolean;
  inventoryEquippable: boolean;
  inventoryConsumable: boolean;
  inventoryStackable: boolean;
};
