import type { CreatureFormState, CreatureSpellcastingProfile } from "../../types";

export const emptyCreatureForm: CreatureFormState = {
  imageAssetId: "",
  avatarUrl: "",
  name: "",
  description: "",
  size: "",
  creatureType: "",
  creatureSubtype: "",
  alignment: "",
  environment: "",
  defaultDisposition: "enemy",
  languages: "",
  walkSpeed: "30",
  swimSpeed: "",
  flySpeed: "",
  burrowSpeed: "",
  climbSpeed: "",
  armorClass: "10",
  hitPoints: "1",
  hitDice: "1d6",
  challengeRating: "",
  xp: "0",
  passivePerception: "10",
  passiveInvestigation: "10",
  passiveInsight: "10",
  abilityScores: {
    str: "10",
    dex: "10",
    con: "10",
    int: "10",
    wis: "10",
    cha: "10",
  },
  savingThrowProficiencies: [],
  skillProficiencies: [],
  skillExpertise: [],
  damageVulnerabilities: [],
  damageResistances: [],
  damageImmunities: [],
  conditionImmunities: [],
  traits: [],
  legendaryDescription: "",
  mythicDescription: "",
  senses: {
    Blindsight: { enabled: false, range: "" },
    Darkvision: { enabled: false, range: "" },
    Tremorsense: { enabled: false, range: "" },
    Truesight: { enabled: false, range: "" },
  },
  spellcastingAbility: "",
  innateSpellcastingAbility: "",
  casterLevel: "0",
  spellSaveDC: "10",
  spellAttackBonus: "0",
  spellSlots1: "0",
  spellSlots2: "0",
  spellSlots3: "0",
  spellSlots4: "0",
  spellSlots5: "0",
  spellSlots6: "0",
  spellSlots7: "0",
  spellSlots8: "0",
  spellSlots9: "0",
  spellRefs: [],
  statBlock: "{}",
};

export function applySpellcastingToForm(
  form: CreatureFormState,
  spellcasting?: CreatureSpellcastingProfile,
): CreatureFormState {
  if (!spellcasting) return form;
  const slotValue = (level: number) => String(Number(spellcasting.slots[String(level)]) || 0);
  return {
    ...form,
    spellcastingAbility: spellcasting.spellcastingAbility,
    innateSpellcastingAbility: spellcasting.innateSpellcastingAbility,
    casterLevel: String(spellcasting.casterLevel),
    spellSaveDC: String(spellcasting.spellSaveDC),
    spellAttackBonus: String(spellcasting.spellAttackBonus),
    spellSlots1: slotValue(1),
    spellSlots2: slotValue(2),
    spellSlots3: slotValue(3),
    spellSlots4: slotValue(4),
    spellSlots5: slotValue(5),
    spellSlots6: slotValue(6),
    spellSlots7: slotValue(7),
    spellSlots8: slotValue(8),
    spellSlots9: slotValue(9),
    spellRefs: spellcasting.spells.map((spell) => ({
      spellId: spell.spellId,
      prepared: spell.prepared,
      innate: spell.innate,
      librarySource: spell.librarySource === "standard" ? "standard" : "user",
      spellLevel: spell.spellLevel,
    })),
  };
}
